# Generated by Django 2.2.2 on 2019-12-19 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wtapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='predicter',
            new_name='predictor',
        ),
    ]
